# Flatten non-top circuits when any pin has an autogenerated name.
# Select on either side; apply the selection to both sides.
sides = [
  ["first", netlist],
  ["second", schematic]
]

selected_names = {}
protected_names = {}

# Inspect both netlists before changing either hierarchy.
sides.each do |side, nl|
  nl.each_circuit do |circuit|
    unless circuit.has_refs?
      protected_names[circuit.name] = true
      next
    end

    total = 0
    generated = 0

    circuit.each_pin do |pin|
      name = pin.name.to_s
      total += 1

      # Empty names, $123, or \$123.
      if name.empty? || name.match?(/\A\\?\$[0-9]+\z/)
        generated += 1
      end
    end

    next unless generated > 0

    selected_names[circuit.name] = true
    puts("Pre-align candidate: #{side} #{circuit.name} " \
         "(#{generated}/#{total} generated pins)")
  end
end

# Protect any circuit name that is top-level on either side.
selected_names.keys.sort.each do |name|
  if protected_names[name]
    puts("Pre-align preserved: #{name} is top-level")
    selected_names.delete(name)
  end
end

sides.each do |side, nl|
  circuits = []

  nl.each_circuit do |circuit|
    if selected_names[circuit.name] && circuit.has_refs?
      circuits << circuit
    end
  end

  circuits.each do |circuit|
    puts("Pre-align flattening: #{side} #{circuit.name}")
  end

  nl.flatten_circuits(circuits) unless circuits.empty?
end

# Namespace generated names only after flattening has inspected original pins.
# Reserve names from both sides so generated names cannot collide with labels.
used_names = {}
sides.each do |_side, nl|
  nl.each_circuit do |circuit|
    circuit.each_net { |net| used_names[net.name.to_s] = true }
    circuit.each_pin { |pin| used_names[pin.name.to_s] = true }
  end
end

sides.each_with_index do |(side, nl), side_index|
  prefix = side_index == 0 ? '__a' : '__b'
  serial = 0
  renamed_net_count = 0
  renamed_pin_count = 0
  fresh_name = lambda do |stem = ''|
    loop do
      serial += 1
      candidate = "#{stem}#{prefix}_#{serial}"
      next if used_names[candidate]
      used_names[candidate] = true
      break candidate
    end
  end
  generated_name = lambda do |name|
    name.empty? || name.match?(/\A\\?\$[0-9]+\z/)
  end

  nl.each_circuit do |circuit|
    # Count distinct spellings, not the net and its pin as two occurrences.
    names = {}
    circuit.each_net { |net| names[net.name.to_s] = true }
    circuit.each_pin { |pin| names[pin.name.to_s] = true }
    groups = Hash.new { |hash, key| hash[key] = [] }
    names.each_key do |name|
      next if generated_name.call(name)
      base = name.sub(/\\?\$[0-9]+\z/, '')
      groups[base] << name
    end
    duplicate_names = {}
    groups.each_value do |members|
      next unless members.size > 1
      members.each { |name| duplicate_names[name] = true }
    end
    renamed_names = {}
    renamed_nets = {}
    circuit.each_net do |net|
      old_name = net.name.to_s
      next unless generated_name.call(old_name) || duplicate_names[old_name]
      new_name = fresh_name.call(duplicate_names[old_name] ? old_name : '')
      renamed_names[old_name] = new_name unless old_name.empty?
      renamed_nets[new_name] = true
      net.name = new_name
      renamed_net_count += 1
    end
    circuit.each_pin do |pin|
      old_name = pin.name.to_s
      next unless generated_name.call(old_name) || duplicate_names[old_name]
      connected = circuit.net_for_pin(pin.id)
      connected_name = connected ? connected.name.to_s : nil
      new_name = if renamed_nets[connected_name]
                   connected_name
                 else
                   renamed_names[old_name] || fresh_name.call(duplicate_names[old_name] ? old_name : '')
                 end
      circuit.rename_pin(pin.id, new_name)
      renamed_pin_count += 1
    end
  end
  puts("Pre-align renames: #{side} #{renamed_net_count} nets, #{renamed_pin_count} pins (prefix #{prefix}_)" )
end
